### ISSUE TITLE
undefined method `alias_method_chain' for #<Class:ActiveRecord::Base>

### ISSUE THREAD

**Issue by mateuspiresl** [markets/unscoped_associations#22]
Just installed unscoped_associations and got this error when trying to start rails or run the console.
Didn't change any other code, just included the package in the Gemfile and installed.

```
/<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/unscoped_associations-0.6.5/lib/unscoped_associations.rb:7:in `block in included': undefined method `alias_method_chain' for #<Class:ActiveRecord::Base>
Did you mean?  alias_method (NoMethodError)
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/unscoped_associations-0.6.5/lib/unscoped_associations.rb:6:in `instance_eval'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/unscoped_associations-0.6.5/lib/unscoped_associations.rb:6:in `included'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/unscoped_associations-0.6.5/lib/unscoped_associations.rb:61:in `include'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/unscoped_associations-0.6.5/lib/unscoped_associations.rb:61:in `block in <top (required)>'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/unscoped_associations-0.6.5/lib/unscoped_associations.rb:61:in `instance_eval'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/unscoped_associations-0.6.5/lib/unscoped_associations.rb:61:in `<top (required)>'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `require'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
	from /<my home>/<my project>/config/application.rb:17:in `<top (required)>'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /<my home>/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
Rails 5.1.7

**Comment by markets** [comment]
Hi @mateuspiresl 👋 this gem is not compatible with Rails 5.1 (and up), as per the docs and the gemspec: 

https://github.com/markets/unscoped_associations/blob/525593d4f3b45a759ff523744eea848f3d952d8d/unscoped_associations.gemspec#L18

See more info in these issues:

- #21
- #19

If you need a Rails 5.1+ compatible version, you can check other forks: https://github.com/markets/unscoped_associations/network

Thanks.
